export * from './content/html.pipe';
export * from './content/shruggie.pipe';
export * from './crypto/effort.pipe';
export * from './crypto/hashLink.pipe';
export * from './crypto/hashrate.pipe';
export * from './crypto/toCoin.pipe';
export * from './date/timeAgo.pipe';
export * from './math/removeTrailingZeros.pipe';
export * from './pipes.module'
