name: Lethean Desktop build
permissions:
  contents: write
on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build: [
          { name: Lethean, platform: linux/amd64, os: ubuntu-latest },
          { name: Lethean, platform: windows/amd64, os: windows-latest },
          { name: Lethean, platform: darwin/universal, os: macos-latest }
        ]
    runs-on: ${{ matrix.build.os }}
    steps:
      # Checkout code
      - uses: actions/checkout@v2
        with:
          repository: 'letheanVPN/wallet'
          submodules: recursive
      - uses: dAppServer/pwa-native-action@main
        with:
          pwa-build: ${{ github.workspace }}
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}
